const { withAppBuildGradle } = require('expo/config-plugins');

// `android/` is generated by `expo prebuild`, so a signing config edited into
// android/app/build.gradle by hand is wiped on the next prebuild. This plugin
// re-applies it every time, and reads the keystore location and passwords from
// `release-keystore.properties` at the project root (gitignored) so no secret
// ever lands in a generated — or committed — file.
//
// With no properties file present the release build still works: it falls back
// to the debug keystore, exactly as the stock Expo template does.

const LOAD_PROPS = `    def releaseKeystoreProps = new Properties()
    def releaseKeystorePropsFile = rootProject.file('../release-keystore.properties')
    if (releaseKeystorePropsFile.exists()) {
        releaseKeystorePropsFile.withInputStream { releaseKeystoreProps.load(it) }
    }

`;

const SIGNING_ANCHOR = `    signingConfigs {
        debug {`;

const DEBUG_BLOCK_END = `            keyPassword 'android'
        }
    }`;

const RELEASE_SIGNING = `            keyPassword 'android'
        }
        if (releaseKeystoreProps['storeFile']) {
            release {
                storeFile rootProject.file('../' + releaseKeystoreProps['storeFile'])
                storePassword releaseKeystoreProps['storePassword']
                keyAlias releaseKeystoreProps['keyAlias']
                keyPassword releaseKeystoreProps['keyPassword']
            }
        }
    }`;

const RELEASE_BUILD_TYPE = `        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const RELEASE_BUILD_TYPE_SIGNED = `        release {
            signingConfig releaseKeystoreProps['storeFile'] ? signingConfigs.release : signingConfigs.debug`;

function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;

    if (contents.includes('releaseKeystoreProps')) {
      return config;
    }

    for (const anchor of [SIGNING_ANCHOR, DEBUG_BLOCK_END, RELEASE_BUILD_TYPE]) {
      if (!contents.includes(anchor)) {
        throw new Error(
          'withReleaseSigning: android/app/build.gradle does not look the way this ' +
            'plugin expects. The Expo template changed; update plugins/withReleaseSigning.js.\n' +
            `Missing anchor:\n${anchor}`
        );
      }
    }

    contents = contents.replace(SIGNING_ANCHOR, LOAD_PROPS + SIGNING_ANCHOR);
    contents = contents.replace(DEBUG_BLOCK_END, RELEASE_SIGNING);
    contents = contents.replace(RELEASE_BUILD_TYPE, RELEASE_BUILD_TYPE_SIGNED);

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withReleaseSigning;
